### PR TITLE
chore(build): swap in tsdx

### PR DESCRIPTION
**Pull request by RichiCoder1**
There's still work that needs to happen as when I last worked on this there were still some important differences in the output around externals, but I figured I'd issue this PR so one can see the differences in a rough state.

/cc @markerikson

### CODE REVIEW

**Comment by markerikson** [comment]
Great, thanks! What are the differences in output atm?

**Comment by markerikson** [comment]
I'm poking around at this, and I'm seeing some failing type tests that... shouldn't be.

In particular, these for `createSlice`:

```ts
  // typings:expect-error
  const stringReducer: Reducer<string, PayloadAction<number>> = slice.reducer
  // typings:expect-error
  const anyActionReducer: Reducer<string, AnyAction> = slice.reducer
```

@phryneas , any idea why these are failing?  Not sure if it's due to a TS update, or the fact that we're using TS directly now.

Also, I see that `ts-jest` is flagging unused variables in tests as errors, which seems overly strict (especially when a few of the tests are doing things like grabbing `extraArg` from a thunk and asserting on it, and not using `dispatch` or `getState`).  That's... annoying.

**Comment by RichiCoder1** [comment]
> Great, thanks! What are the differences in output atm?

I think the biggest difference is you had externals for a few of the packages setup differently than how it's currently configured. I forget the specifics. I think there's also at least one rollup plugin I hadn't brought over yet.

> I'm poking around at this, and I'm seeing some failing type tests that... shouldn't be.

> In particular, these for createSlice:

Weird. Maybe a typescript bump error? 

> Also, I see that ts-jest is flagging unused variables in tests as errors, which seems overly strict (especially when a few of the tests are doing things like grabbing extraArg from a thunk and asserting on it, and not using dispatch or getState). That's... annoying.

That should be pretty easy to fix, just need to crank that option down.

**Comment by markerikson** [comment]
Yeah, looking at the build output, the biggest immediate differences I see are:

- The names of the UMD files changed (`r-s-k.umd[.min].js` for current, `r-s-k.umd[.development].js` for  this branch)
- The UMD files are no longer embedding the other libs directly, but rather expecting them as globals

I'm not as overly concerned about the UMD naming, especially since this is pre-1.0, but I do want our UMD files to be entirely self-contained (ie, I should be able to link the UMD file and write working Redux code right there).

**Comment by RichiCoder1** [comment]
I think both are those are pretty fixable. Just need to drop the externals plugin from the UMD build and tweak the output name. I can try both those later.

**Comment by phryneas** [comment]
> ```ts
> stringReducer
> ```

Seems to be a bug introduced with TypeScript 3.6. State is inferred to `any` in that version, no matter what is being passed in. No idea why though. That'll need some investigation.

**Comment by markerikson** [comment]
Bah, closed by the TS fix PR.  Reopening.

**Comment by markerikson** [comment]
Welllll, something is definitely still not right here:

```
    src/createSlice.test.ts:104:42 - error TS2769: No overload matches this call.
      Overload 1 of 2, '(payload?: undefined): WithPayload<undefined, Action<"ADD_MORE">>', gave the following error.
        Argument of type '{ amount: number; }' is not assignable to parameter of type 'undefined'.
      Overload 2 of 2, '(payload?: void | undefined): WithPayload<void, Action<"ADD_MORE">>', gave the following error.
        Argument of type '{ amount: number; }' is not assignable to parameter of type 'void'.
    104       const result = reducer(10, addMore({ amount: 5 }))
                                                 ~~~~~~~~~~~~~
```

**Comment by markerikson** [comment]
Well, it builds now!

I fixed the now-broken uses of `createAction`, and patched up the types in `createReducer.test.ts` enough to let it run.  (The point of that file is to test _behavior_, not the types, so I'm not worried if it's a little iffy.)

So, now the question is what the output is like.

I gotta head to bed, but will hopefully be able to look at it again tomorrow.

**Comment by markerikson** [comment]
Okay, fixed up the UMD externals and the dev filename.  Output now looks basically equivalent to what we have already, minus a few Babel helpers and such.  

Also, interestingly, the CJS file appears to already be minified, which is surprising.

I'm going to publish an alpha build and see if we can get some folks to test it out.

**Comment by markerikson** [comment]
Published `v0.9.0-alpha.0` as `redux-starter-kit@build-test`.

Can folks try it out and see how it looks?

**Comment by phryneas** [comment]
You can look at the files in the package over at https://unpkg.com/browse/redux-starter-kit@0.9.0-alpha.0/ :

I'm not really happy that we're shipping the src folder (I already know I'll be importing from there on accident), and in addition to that all those .d.ts files seperately instead of a rolled-up .d.ts (I already know that those will be problems with my `babel`+`babel-preset-typescript` webpack setup :cry: ).

@nickmccurdy can we do a rollup from that? This seems to be an open issue with https://github.com/jaredpalmer/tsdx/issues/80 - that's why I personally prefer `pika` with `@pika/plugin-bundle-types` over `tsdx`. But maybe we could take some inspiration from jaredpalmer/jsdx#80 or how @pika/plugin-bundle-types does it?

**Comment by phryneas** [comment]
As this is a quite exotic case, I've created a reproduction repo here: https://github.com/phryneas/reproduction-non-rollup-types/blob/master/src/index.ts

Given that by now, almost everything is re-exported from index.d.ts, I don't actually think this is too much of a problem any more (it was in the early days of RSK for me and I still have some workarounds for that in place!), but I'd love to see the types as one single file for 1.0.

**Comment by phryneas** [comment]
> @phryneas I personally haven't been able to get rollup to generate a bundled `.d.ts` file. The issue is that the declarations are generated by the TS compiler, which isn't a bundler and cannot concatenate the files. Still, TypeScript will work fine with multiple `.d.ts` files even if there's only a single `.js` entry file.

TS itself works perfectly - but webpack can crash like in the reproduction above when using babel-loader or ts-loader with isolatedModules when provoking some edge cases.
 
There's a trail of issues in those loaders' repos, but there isn't much the loaders can do about it themselves. But as I said, at the current state it's probably fine, even though I suspect we will have some stray error reports over the next moths.

**Comment by markerikson** [comment]
Why are multiple types files problematic for certain build setups?

FWIW, unless this is a huge problem with this PR, my intent is to merge it, publish an RC or two, and get 1.0 out the door in the next few days.

**Comment by phryneas** [comment]
@markerikson tanspilation is often done without file-spanning typechecking to save time (and doing the typechecking in a second thread). While that is much faster, the transpiler has no information if a certain import is a type, or a value. Most of the time, that can be seen from the context the value/type is used within the file, but there are scenarios (directly re-exporting an imported type, for example) where that is not possible.
That, in combination with a bundler can lead to problems, as can be seen when trying to build my reproduction (in the editor, it looks fine).

While not critical (and nothing that should stop you from publishing 1.0), as I said, I would really like RSK to have a single-file output to prevent such problems.
I guess I'll give it a timeboxed spin, maybe I can make this work in a short amount of time.

**Comment by phryneas** [comment]
Okay, doing a dts-rollup with api-extractor works without any modifications to the RSK sources.

That would mean these changes to the build: https://github.com/RichiCoder1/redux-starter-kit/compare/switch_to_tsdx...phryneas:dtsRollup?expand=1

build output would look like this: https://unpkg.com/browse/@phryneas/experimental-redux-starter-kit@0.8.1-donotuse-dtsRollup-2/dist/

**Comment by phryneas** [comment]
Oh, and one thing that is definitely a bug and needs to be adressed:
This file https://unpkg.com/browse/redux-starter-kit@0.9.0-alpha.0/dist/index.js links to `./redux-starter-kit.cjs.production.min.js`, which does not exist.

**Comment by markerikson** [comment]
@phryneas : y'know, I just realized that's why we only have a minified CJS file.  It's because the custom Rollup config is overriding the output in both cases, by reading from one of the `package.json` fields.  We'd want to change the `package.json` field to point to `index.js` instead.

**Comment by markerikson** [comment]
Been working on this this evening.  Fixed the CJS filename, and was working on copying the changes @phryneas suggested.

I just updated TSDX to 0.10.x on general principle... and it looks like it's now bundling all the typedefs into `index.d.ts` automatically due to a change in Rollup TS plugins, no `api-extractor` package needed:

https://github.com/jaredpalmer/tsdx/issues/200

https://github.com/jaredpalmer/tsdx/pull/208

Based on that, I'm going to drop it from the setup for now.  If someone wants to see what other options it offers down the road, I'm fine with that.

**Comment by markerikson** [comment]
Oooo-kay, and that's _completely_ dying in the tslint check with:

`Definition for rule '@typescript-eslint/no-angle-bracket-type-assertion' was not found  @typescript-eslint/no-angle-bracket-type-assertion`

For _every_ TS source file.  What in the world?

**Comment by markerikson** [comment]
Whoa, this is bizarre.  That actually showed up previously over in #198 .

**Comment by markerikson** [comment]
Still don't know what's _causing_ that weird lint error, but I was able to shut it up by explicitly disabling that lint rule.

**Comment by markerikson** [comment]
yayyyyyy and we're green!

okay, I'm gonna go publish another alpha now.

**Comment by markerikson** [comment]
Okay, `v0.9.0-alpha.1` is out.  Unpkg looks good:

https://unpkg.com/browse/redux-starter-kit@0.9.0-alpha.1/dist/

**Comment by markerikson** [comment]
Tried forking the last "Advanced Tutorial" sandbox and updating it to `v0.9.0-alpha.1`.  Fixed the `slice` -> `name` changes, and it runs.

Any further comments or objections before I merge this in and publish 0.9.0?

**Comment by phryneas** [comment]
I'd publish it as 0.9 - that way we get some real-world feedback until you publish it as 1.0

**Comment by markerikson** [comment]
Agreed.  All right, I'll merge this in and put out 0.9.

**Comment by markerikson** [comment]
Published https://github.com/reduxjs/redux-starter-kit/releases/tag/v0.9.0

**Comment by RichiCoder1** [comment]
@markerikson Glad I could be of help!

**Comment by markerikson** [comment]
Yep, thanks!

**Pull request merged**
