### PR TITLE
Typescript support

### LINKED ISSUE #28: Support Redux 4
Redux 4 is out. The tests already pass using it, ~~but `redux-devtools-extension` needs to update its peer dependency (blocked by https://github.com/zalmoxisus/redux-devtools-extension/pull/490). I'd like wait until this is fixed before adjusting our peer dependencies to reduce confusion and limit peer dependencies seen by users,~~ this issue is just here to remind us to adjust the peer dependency after `redux-devtools-extension` updates.

### LINKED ISSUE #30: Typing support
A lot of Redux users use TypeScript or Flow, and with Redux 4 out, I think it would be a good idea to provide optional types for this module. I would personally prefer to start by porting the codebase to TypeScript, but we could use separate definition files if desired. I may give this a shot but I want to wait for feedback and fix #28 first.

### PR DESCRIPTION
**Pull request by nickmccurdy**
I would appreciate code reviews but please do not merge yet.

- [x] Strictly type with TypeSscript 3 (does not support TypeScript 2)
- [x] Use Babel 7 to retain similar build tooling
- [x] Attempt to make createReducer Action types safe (requires complex mapped types and inference)
- [x] Set up declaration publishing
- [ ] Finish typing [selectorator](https://github.com/planttheidea/selectorator)

- Fixes #28
- Fixes #30

### CODE REVIEW

**Comment by nickmccurdy** [comment]
I think I finally got the action types in a decent state. 😄 The disadvantage is that in TS files createReducer now requires both its generic arguments (state type and union of action types), but it maps each slice reducer's key to the appropriate action type so slice reducer arguments can be inferred. Usage in JS files should be unaffected, though I'm not 100% sure if I got the Babel 7 config working with external helpers properly.

Declaration files are also added to dist in the install script, so types should be published automatically. The normal JS builds still work without the TS compiler or Babel preset.

I'd appreciate a code review, but I still need to finish selectorator before this can be merged.

**Comment by nickmccurdy** [comment]
@neurosnap By the way thanks for your advice on createReducer types, here's what I have so far: https://github.com/nickmccurdy/redux-starter-kit/blob/typescript/src/createReducer.ts

**Comment by nickmccurdy** [comment]
I'd be happy to update this if we can switch from Selectorator to Reselect

**Comment by markerikson** [comment]
Remind me what the specific difficulties are in adding types to Selectorator?

**Comment by markerikson** [comment]
@nickmccurdy : *ping*

What are the specific problems typing Selectorator?  Is it primarily the multiple-parameters issue?

What would be your thoughts on cloning Selectorator into the lib, and maybe enforcing _only_ passing the input selectors as an array instead of multiple args?

**Comment by markerikson** [comment]
Superseded by #73 .

**Pull request closed without merging**
