### PR TITLE
Test with multiple TypeScript minor versions in CI

### LINKED ISSUE #216: Update Travis to test against multiple versions of TypeScript
References: 

- https://github.com/reduxjs/redux-starter-kit/issues/82#issuecomment-542334266

> Could we please have the build & tests run for multiple TS versions? Something like the last 4 or 5 minor releases should catch quite a few bugs.

- #214
- #212

/cc @phryneas

### PR DESCRIPTION
**Pull request by nickmccurdy**
Fixes #216

- [x] Add build matrix to Travis for multiple TypeScript versions
- [ ] Update development version to 3.6

### CODE REVIEW

**Comment by markerikson** [comment]
Seems pretty straightforward, and the Travis run for this PR definitely ran for each of those.  Anything else needed to tweak this?

**Comment by nickmccurdy** [comment]
Oops the `after_install` script that actually installs the right TypeScript version isn't working for some reason, I'll look into this

**Comment by nickmccurdy** [comment]
The multiple TypeScript versions are being installed properly now, but the type tests fail on TypeScript 3.6. Should we try to fix it with this PR or use 3.5 as the max for now?

**Comment by markerikson** [comment]
Merge down from master - I merged in #215 , which should hopefully fix that.

**Comment by markerikson** [comment]
Yep, that passes now.  Should be good to go!

**Pull request merged**
