### PR TITLE
Create slice changes

### PR DESCRIPTION
**Pull request by phryneas**
These are the changes you requested over in #82

### CODE REVIEW

**Comment by markerikson** [comment]
Great, thanks!

Ironically, I'm actually having second thoughts about the "return the reducer" thing:

https://twitter.com/acemarke/status/1175881949514219521

It's an interesting idea, and yet at the same time I'm not sure it buys much actual improvement.

Thoughts?

**Comment by phryneas** [comment]
It's definitely nicer to use (took my a while to figure out that I could not use the slice directly in combineReducers), but the console.log in chrome is really bad :/
(Firefox works though: https://imgur.com/mIipct5 )

What about turning the idea around? Export a modified combineReducers from RSK that takes either functions or slices?

**Comment by markerikson** [comment]
No, one of the main points of RSK is that it's "just Redux".  I don't want to have a special version of `combineReducers`.

Y'know, I think I've talked myself out of returning the reducer directly.  Returning the object gives us a bit more flexibility in case we ever do add something else to `createSlice`, and I don't think there's all that much benefit in returning the reducer by itself.  Let's drop that and just do the `slice? -> name` change.  

Sorry for the whiplash :)

**Comment by markerikson** [comment]
@phryneas : just re-read your comment in the 1.0 thread.  

Yeah, sure, let's go ahead and include the individual reducers in the slice object (which is also another argument for keeping it as an object).

**Comment by phryneas** [comment]
@markerikson okay. I'll revert the "reducer function" commit so that this can get merged and open a separate PR for the `caseReducers` (I think that name is fine) in the coming days.

**Comment by markerikson** [comment]
One additional request: can we throw an error if `name` is falsy?  That would force the user to add a non-empty name.

**Comment by markerikson** [comment]
Awright, looks good to me!

**Pull request merged**
