### PR TITLE
Allow consumer to augment middleware to tolerate certain structures (e.g. Immutable)

### PR DESCRIPTION
**Pull request by kgregory**
In Issue #140 I said I would wait before submitting a PR, but here we are.

This pull request will enhance `serializable-state-invariant-middleware` to accept an additional option at creation: `getEntries`.  Additionally, it will use the `isSerializable` when checking action and state.

These two options will allow a consumer to augment the middleware to tolerate certain structures, such as ImmutableJS.  In the example below, the consumer is configuring the middleware to permit `immutable` structures and consider them to be serializable:

```js
// immutable version 3.8.2 assumed for this demo!
const isSerializable = (value: any): boolean =>
  Iterable.isIterable(value) || isPlain(value);

const getEntries = (value: any): [string, any][] =>
  Iterable.isIterable(value) ? value.entries() : Object.entries(value);

const middleware = createSerializableStateInvariantMiddleware({
  isSerializable,
  getEntries,
});
```

### CODE REVIEW

**Comment by kgregory** [comment]
Additional commit to amend docs for new middleware option

**Comment by mayteio** [comment]
Anything holding this back from being merged?

**Comment by markerikson** [comment]
@mayteio : me, mostly :)  I've been swamped with work, spent the couple weeks prepping for a conference talk, just gave that, and will be doing more traveling the next few days.  I haven't had time to sit down and play maintainer for RSK.

Hopefully I'll have some time in the next couple weeks.

**Comment by kgregory** [comment]
@markerikson haven't pushed on this because of exactly those reasons.  You do a crazy amount of good work that helps so many developers.  Thanks for that!

**Comment by markerikson** [comment]
Okay, seems reasonable.  Merging.

**Pull request merged**
