### PR TITLE
add docs for createAction.match

### PR DESCRIPTION
**Pull request by phryneas**
Writing docs is not my strong suit, so if you have any better ideas, I'm all for it :)

Also, I'm not a user of `redux-observable` myself, so maybe @on3iro has a better idea for a redux-observable example here?

### CODE REVIEW

**Comment by markerikson** [comment]
Drat, I actually meant to do this on the docs tweak branch I was working on a few minutes ago, and forgot :) 

Thanks!

**Comment by markerikson** [comment]
Travis failure is due to formatting - just re-run Prettier.

Also, can you add a brief mention that the type guards might be particularly useful in a custom middleware as well?  I was actually just dealing with this a couple days ago.

**Comment by phryneas** [comment]
> Travis failure is due to formatting - just re-run Prettier.

:+1: 

> Also, can you add a brief mention that the type guards might be particularly useful in a custom middleware as well? I was actually just dealing with this a couple days ago.

Good idea, added a sentence :)

**Comment by markerikson** [comment]
Thanks!

**Comment by phryneas** [comment]
@on3iro - while this is already merged, if you have a better idea for a redux-observable example, a PR is very welcome!

**Comment by on3iro** [comment]
@phryneas the example looks good to me :+1:

**Pull request merged**
