### PR TITLE
initial work on create slice

### PR DESCRIPTION
**Pull request by neurosnap**
Extracted from this comment: https://github.com/markerikson/redux-starter-kit/issues/17#issuecomment-414543588

#17

### CODE REVIEW

**Comment by neurosnap** [comment]
I updated the PR with the requested changes.  I also added some tests.  Happy to make more changes as recommended.

**Comment by nickmccurdy** [comment]
Thanks. So the goal compared to createReducer is to bundle in actions instead of just returning a merged slice reducers, right? Do you think we could make the API more like createReducer with initialState, actionsMap, and slice as ordered args? Also, why is the slice property in the retuend bundled?

**Comment by neurosnap** [comment]
So to clarify you would like to see: 

```
const counter = createSlice({
  initialState,
  actionsMap,
  slice,
});
```

I added slice as a way to get the slice back as a const if a string literal was used inside the `createSlice` function.  I can remove that.

**Comment by nickmccurdy** [comment]
Ah, so it's just for namespacing actions? That sounds like it could still be useful.

@markerikson What do you think about this API for wrapping createReducer in reducer and action bundles with optional slice based namespacing?

**Comment by markerikson** [comment]
Uh... yes, that was exactly the point in the first place :)  Like `autodux`, but using our own `createReducer` internally.

**Comment by nickmccurdy** [comment]
Cool, I'm in favor of merging as long as we can get the order in https://github.com/markerikson/redux-starter-kit/pull/37#issuecomment-419762825

**Comment by markerikson** [comment]
I think I'd prefer a single "options object" rather than multiple positional arguments for this API.

**Comment by nickmccurdy** [comment]
`createReducer` already has a signature of `(initialState, actionsMap)`, so I'd prefer to stay consistent by either following the order in https://github.com/markerikson/redux-starter-kit/pull/37#issuecomment-419762825 or also converting `createReducer` to an options object signature.

**Comment by neurosnap** [comment]
options object makes sense to me personally, but I don't care either way.

This library also has nothing to do with creating selectors like autodux does, so it is not at perfect parity.  I personally think that auto-generating selectors will really bloat this code and beyond a root selector for each slice I wouldn't add anything more than that.

**Comment by neurosnap** [comment]
Also, it might be useful to write a little helper for creating actions that anyone can use.  Example:

```js
export default function createAction(type) {
  const action = (payload) => ({
    type,
    payload,
  });

  action.toString = () => `${type}`;
  return action;
}
```

This will allow us to stringify the action returned from `createSlice` and is something very similar to what autodux does.  This will allows `createSlice` to work with libraries like `redux-saga`

**Comment by markerikson** [comment]
I'd actually like to clone the "create selectors automatically" functionality if we could.

**Comment by neurosnap** [comment]
Ok, if it's alright with you I would prefer to add that in as a separate PR.  It seems distinct enough to be its own feature.

**Comment by markerikson** [comment]
Superseded by the work done on `robodux` and ported directly to `redux-starter-kit`, as discussed in #17 .  @neurosnap , thanks for writing `robodux` and allowing us to port that over!

**Pull request closed without merging**
